config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    patch '/users/:id', to: 'users/registrations#update'
  end

  root to: "events#index"
  resources :events, only: [:index, :new, :create, :show, :edit, :update] do
  end

  resources :users, only: [:show]

  resources :events do
    resources :messages, only: [:create]
  end

  # resources :maps, only: [:index]

end

app/models/event.rb
class Event < ApplicationRecord

    #active_hashとの紐づけ
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :gender
    belongs_to :prefecture
    belongs_to :generation
    belongs_to :duration
    belongs_to :status

    validates :title, presence: true
    validates :description, presence: true, length: { maximum: 300 }
    validates :prefecture_id, presence: true, numericality: {other_than: 1}
    validates :date, presence: true
    validates :start_time, presence: true
    validates :duration, presence: true
    validates :address, presence: true
    
    #geocoderの設定
    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    #アソシエーション
    belongs_to :user
    has_many :messages

    # 検索機能の条件分岐
    def self.search(search1,search3)
        if search1 == nil &&  search3 == nil
            Event.all 
        elsif search1 == "1" &&  search3 == "0"
            Event.all 
        elsif search1 >= "2" &&  search3 ==  "0"
            Event.where(prefecture_id: search1 )
        elsif search1 == "1" &&  search3 >=  "1"
            Event.where(duration_id: search3 )
        else
            Event.where(prefecture_id: search1 , duration_id: search3 )
        end
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :show, :edit ]

  def index
  @event = Event.search(params[:search1], params[:search3] ).order("date ASC")
  # 検索が空欄の時は、全部取ってくるようにモデルに設定済
  end

  def new
  @event = Event.new
  end

  def create
  @event = Event.create(event_params)
   if @event.save
    redirect_to root_path
   else
    render :new, status: :unprocessable_entity
   end
  end

  def show
    @event = Event.find(params[:id])
    @message = Message.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
    redirect_to event_path(@event.id)
    else
    render :edit, status: :unprocessable_entity
    end
  end

  # def search
    # @event = Event.search(params[:search1], params[:search3] )
  # end
  
  private
  
  def event_params
    params.require(:event).permit(:title,:description,:prefecture_id,:date,:start_time,:duration_id,:generation_id,:gender_id,:status_id,:address).merge(user_id: current_user.id)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<head>
  <link rel="stylesheet" href="events/new.css">
</head>

<body>
<div class="main">
  <div class="items-sell-main">
    <div class= "title_box">
    <%= image_tag 'OTOMO_icon_list-04.png', size: "25x25",alt: "list img",class: "icons" %>
    <h3 class="page_title">イベントの編集</h3>
    </div>


<%# イベント説明 %>
    <%= form_with(model: @event, local: true) do |f| %>
          <%# エラーメッセージ %>
          <%= render 'layouts/error_messages', model: f.object %>
    <div class="weight-bold-text">
          ステータス：
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name,  {selected: 1 }, {class:"status_box", id:"item-scheduled-delivery"}) %>
    


    <br><br>
    <h4 style="display:inline">●基本情報</h4> 
    <span class="indispensable">*必須</span>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル：
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"イベント名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベントの説明：
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"イベントの説明（必須 400文字まで)青葉公園で17:00くらいから、犬のお散歩のお伴を探しています！" ,rows:"7" ,maxlength:"400" %>
      </div>
      <div class="weight-bold-text">開催日時：
      </div>
       <%= f.date_field :date, class:"times-text", id:"item-info" %>
       <%= f.time_select :start_time, class:"times-text", id:"item-info" %>
    </div>

    <div class="items-detail">
      
      <div class="form">
        <div class="weight-bold-text">
          所用時間：
        </div>
        <%= f.collection_select(:duration_id, Duration.all, :id, :name, {selected: "1"}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          開催地：
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {selected: current_user.prefecture_id }, {class:"select-box", id:"item-prefecture"}) %>
         <div class="weight-bold-text">
          詳細住所：
        </div>
        <%= f.text_area :address, class:"items-text", id:"address", placeholder:"例）京都市 中京区 OTOMO Cafe" ,maxlength:"50" %>
        <%# 地図%> 
        <br>
        <input type="button" value="地図表示" onclick="codeAddress()">
        <div id="display">※住所を入力し、地図表示ボタンを押してください</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let geocoder
// 下の1行を追加 
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
    //latが緯度、lngが経度を示します
    center: {lat: 35.68123620000001, lng: 139.7671248},
    //数値は0〜21まで指定できます。数値が大きいほど拡大されます
    zoom: 15,
  });

//positionに指定した座標にピンを表示させます
  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      // 下の1行を追加 
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
// ここまで追加 
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>&callback=initMap" async defer></script>
<%# 地図%> 

    <br><br>
    <h4 style="display:inline">●OTOMOの条件</h4> 
    <span class="indispensable">*任意</span>
        <div class="weight-bold-text">
          性別：
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {selected: 3 }, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="items-detail">
      <div class="form">

        <div class="weight-bold-text">
          年齢：
        </div>
        <%= f.collection_select(:generation_id, Generation.all, :id, :name, {selected: 1 }, {class:"select-box", id:"item-shipping-fee-status"}) %> 
        
      </div>
    </div>

    <%# 下部ボタン %>
    <div class="btn_contents">
      <%= f.submit "イベントを編集" ,class:"toroku_btn" %>
      <%=link_to '< back', root_path, class:"back_btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>
</body>

app/views/events/index.html.erb
<head>
   <link rel="stylesheet" href="events/index.css">
</head>

<body>

<div class="main">


  <div class="title-search">
  <%= image_tag 'OTOMO_icon_megane-03.png', size: "25x25",alt: "search img",class: "icons" %>
  <h3 class="midashi">イベントを検索する</h3>
  </div>
  <%# 検索機能 %>
  <div class="search_form">
  <%= form_tag({controller:"events",action:"index"}, method: :get) do %>
    開催地： <%= select_tag :search1, options_for_select(Prefecture.all.map { |p| [p.name, p.id] }, {selected: 1 }), class:"select-box", id:"item-prefecture" %> 
    所用時間： <%= select_tag :search3, options_for_select(Duration.all.map { |p| [p.name, p.id] }, {selected: 0 }), class:"select-box", id:"item-prefecture" %> 
    <%= submit_tag "絞り込み" %>
  <% end %>

  </div>

  <%# 検索条件 %>
  <div class="search_condition"> 
  <% if params[:search1] != nil %>
    ＜検索結果＞
    <div class="conditions">開催地：  <%= Prefecture.find(params[:search1]).name %></div>
  <%else%>
  <%end%>
  <% if params[:search3] != nil %>
    <div class="conditions">所用時間：<%= Duration.find(params[:search3]).name %></div>
  <%else%>
  <%end%>
  </div>

  <br>
   <%# 付近のイベント検索 %>
  <%= form_with(url: "", local: true, method: :get, class: "") do |form| %>
  <%= form.text_field :keyword, placeholder: "例）渋谷駅", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
  <% end %>


    <div class="title-search">
  <%= image_tag 'OTOMO_icon_list-04.png', size: "25x25",alt: "search img",class: "icons" %>
  <h3 class="midashi">すべてのイベント</h3>
  </div>

   <%# 各イベント %>
    <% @event.each do |event| %>
      <li class='list'>
        <div class='event-info'>
          <div class="zone">
          <div class= "status"><%= event.status.name %> </div>
          </div>
        <div class='user_img'>
           <%= image_tag event.user.image, class: "user-icon" if event.user.image.attached? %> 
        </div> 
        <div class='event-daytime'>
          <h3 class='event-name'>
        <%= link_to event_path(event.id) do %>
            <div class="eventname">
            <%= event.title %>
            </div>
        <% end %>
         </h3>
            イベント日時
            <br>
          <span><%= event.date.strftime('%Y/%m/%d') %> <%= event.start_time.strftime( "%H:%M" ) %> ～ </span>
          </div>
        </div> 
      </li>
    <%end%>

</div>

  <%# 募集リンク %>
    <%= link_to(new_event_path, class: 'purchase-btn') do %>
    <%= image_tag 'OTOMO_icon_newevent-06.png', size: '150x150' ,alt: "new event button",class: "newevent" %>
    <% end %>


</body>

app/views/events/new.html.erb
<head>
  <link rel="stylesheet" href="events/new.css">
</head>

<body>
<div class="main">
  <div class="items-sell-main">
    <div class= "title_box">
    <%= image_tag 'OTOMO_icon_list-04.png', size: "25x25",alt: "list img",class: "icons" %>
    <h3 class="items-sell-title">イベントの登録</h3>
    </div>


<%# イベント説明 %>
    <%= form_with(model: @event, local: true) do |f| %>
          <%# エラーメッセージ %>
          <%= render 'layouts/error_messages', model: f.object %>
    <div class="weight-bold-text">
          ステータス：
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name,  {selected: 1 }, {class:"status_box", id:"item-scheduled-delivery"}) %>
    


    <br><br>
    <h4 style="display:inline">●基本情報</h4> 
    <span class="indispensable">*必須</span>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル：
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"イベント名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベントの説明：
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"イベントの説明（必須 400文字まで)青葉公園で17:00くらいから、犬のお散歩のお伴を探しています！" ,rows:"7" ,maxlength:"400" %>
      </div>
      <div class="weight-bold-text">開催日時：
      </div>
       <%= f.date_field :date, class:"times-text", id:"item-info" %>
       <%= f.time_select :start_time, class:"times-text", id:"item-info" %>
    </div>

    <div class="items-detail">
      
      <div class="form">
        <div class="weight-bold-text">
          所用時間：
        </div>
        <%= f.collection_select(:duration_id, Duration.all, :id, :name, {selected: "1"}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          開催地：
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {selected: current_user.prefecture_id }, {class:"select-box", id:"item-prefecture"}) %>
         <div class="weight-bold-text">
          詳細住所：
        </div>
        <%= f.text_area :address, class:"items-text", id:"address", placeholder:"例）京都市 中京区 OTOMO Cafe" ,maxlength:"50" %>
        <%# 地図%> 
        <br>
        <input type="button" value="地図表示" onclick="codeAddress()">
        <div id="display">※住所を入力し、地図表示ボタンを押してください</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let geocoder

const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
    //latが緯度、lngが経度
    center: {lat: 35.68123620000001, lng: 139.7671248},
    //数値は0〜21まで指定可能 数値が大きいほど拡大
    zoom: 17,
  });

//positionに指定した座標にピンを表示
  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>&callback=initMap" async defer></script>
<%# 地図%> 

    <br><br>
    <h4 style="display:inline">●OTOMOの条件</h4> 
    <span class="indispensable">*任意</span>
        <div class="weight-bold-text">
          性別：
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {selected: 3 }, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="items-detail">
      <div class="form">

        <div class="weight-bold-text">
          年齢：
        </div>
        <%= f.collection_select(:generation_id, Generation.all, :id, :name, {selected: 1 }, {class:"select-box", id:"item-shipping-fee-status"}) %> 
        
      </div>
    </div>

    <%# 下部ボタン %>
    <div class="btn_contents">
      <%= f.submit "イベントを登録" ,class:"toroku_btn" %>
      <%=link_to '< back', root_path, class:"back_btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>
</body>

app/views/events/show.html.erb
<head>
<%# イベント詳細ページ %>
<link rel="stylesheet" href="events/show.css">
</head>


<body>
  <div class="main">
  
    <div class="title-search">
    <%= image_tag 'OTOMO_icon_nico-02.png', size: "25x25",alt: "search img",class: "icons" %>
    <h3 class="midashi">イベントの詳細</h3>
    </div>

 
      <div class='info_box'>
        <%# user info %>
          <div class='user_info'> 
            <%= link_to user_path(@event.user.id) do %>
            <%= image_tag @event.user.image, class: "user-icon" if @event.user.image.attached? %> 
            <% end %>
            <div class="user_name">
            <%= @event.user.nickname %>
            </div>
          </div>
       <div class="hissu_info">
        <div class="sta_edi">
            <div class="status">
            <%= @event.status.name %>
            </div>
            
         <%# 編集リンク %>
         <% if @event.user.id == current_user.id %>
           <%= link_to(edit_event_path(@event.id), class: 'edit_btn') do %>
            <span class='edit_btn_text'>イベントを編集</span>
           <% end %>
         <% end %>
        </div>

        <div class="titledis">
            <h3>
            <%= @event.title %>
            </h3>            
            <%= @event.description %>
        </div>
       </div>
      </div>

    <div class='locate_info'>
          <h4>●基本情報</h4>
          イベント日時：
          <span><%= @event.date.strftime('%Y/%m/%d') %>   <%= @event.start_time.strftime( "%H:%M" ) %> ～ (所用時間： <%= @event.duration.name %>) </span>
          <br>
          開催地：    <%= @event.prefecture.name %>
          <br>
          詳細住所： <%= @event.address %>
    </div>
    <div class='ninni_info'>
          <h4>●OTOMOの条件</h4>
          性別： <%= @event.gender.name %>
          <br>
          年齢： <%= @event.generation.name %>
    </div>
      
    

  
     <h4 class= "message_info">●メッセージ</h4>
  <div class="comments">
   <div class="nakami">
      <div class="attention">
      <div>主催者にメッセージを送って質問や参加希望を伝えましょう</div>
      </div>
    
    <% @event.messages.each do |message| %>
    <div class="one_come">
        <%= link_to user_path(message.user.id) do %>
        <%= image_tag message.user.image , class: "commenter_icon" %>  
        <%end%>
      <div class="comment">
        <p class="commenter_name"><%= message.user.nickname %></p>
        <p class="comment_text"><%= message.content%></p>
      </div>
    </div>
    <% end %>
   </div>
    <div class= "onegai"><p>参加者が決まったらイベント編集ページからステータスを「募集終了」に変更しましょう</p>
    </div>
  </div>

      <div class="comment_zone">
    <%= form_with model: [@event, @message] do |f| %>
      <%= f.text_area :content , placeholder:"例）参加希望です！もし参加可能でしたら、集合場所を教えてください。", class: "comment_form"%>
      <div class="submit_btn">
      <%= f.submit "メッセージ送信", class: "comment_submit" %>
      </div>
      <% end %>
      </div>

  </div>
</body>